


import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navber from "@/components/Navbar";
import Footer from "@/components/Footer"
import  {LanguageProvider}  from "@/context/LanguageContext"
import { CurrencyProvider } from "@/context/CurrencyContext";






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       

        <LanguageProvider>
        <CurrencyProvider>
        <Navber/>
        {children}
        <Footer/>
        </CurrencyProvider>
       </LanguageProvider>
      
      </body>
    </html>
  );
}
